-- Migration: Add identity_narrative column to brand_profiles
-- Run this in your Supabase SQL editor before deploying the brand profile pages.
--
-- The identity_narrative column stores a 2-3 sentence AI-generated prose
-- description of each brand's identity, generated by GPT-4o-mini on first visit
-- and cached here for subsequent page loads.

ALTER TABLE brand_profiles
  ADD COLUMN IF NOT EXISTS identity_narrative TEXT;

COMMENT ON COLUMN brand_profiles.identity_narrative IS
  'AI-generated 2-3 sentence identity narrative (GPT-4o-mini). Generated on first page visit and cached.';
